# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
#   http_method_override je po default-u setovan na false , postavljanjem na true omogucava se da fejkujemo http zahteve i posaljemo
#    PUT, DELETE  itd zahteve koristeci  hidden input polje u formi sa name=_method i value=zahtev koji hocemo da posaljemo
    http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
